### ISSUE TITLE
Object #<Metalsmith> has no method 'join'

### ISSUE THREAD

**Issue by charlespeters** [segmentio/metalsmith-templates#46]
not sure what's going on with this error after running make build

```
node_modules/.bin/metalsmith

  Metalsmith · Object #<Metalsmith> has no method 'join'

TypeError: Object #<Metalsmith> has no method 'join'
    at convert (/Users/charles/Desktop/new-metalsmith-blog/node_modules/metalsmith-templates/lib/index.js:42:29)
    at /Users/charles/Desktop/new-metalsmith-blog/node_modules/metalsmith-templates/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (/Users/charles/Desktop/new-metalsmith-blog/node_modules/metalsmith-templates/node_modules/async/lib/async.js:32:24)
    at async.each (/Users/charles/Desktop/new-metalsmith-blog/node_modules/metalsmith-templates/node_modules/async/lib/async.js:110:9)
    at Ware.<anonymous> (/Users/charles/Desktop/new-metalsmith-blog/node_modules/metalsmith-templates/lib/index.js:33:5)
    at Ware.<anonymous> (/Users/charles/Desktop/new-metalsmith-blog/node_modules/metalsmith/node_modules/ware/node_modules/wrap-fn/index.js:45:19)
    at Object.next (/Users/charles/Desktop/new-metalsmith-blog/node_modules/metalsmith/node_modules/ware/lib/index.js:75:20)
    at Object._onImmediate (/Users/charles/Desktop/new-metalsmith-blog/node_modules/metalsmith/node_modules/ware/node_modules/wrap-fn/index.js:121:18)
    at processImmediate [as _immediateCallback] (timers.js:354:15)

make: *** [build] Error 1

```

**Comment by jme783** [comment]
+1, having the same issue

**Comment by charlespeters** [comment]
i resolved this on my end my deleting the node_modules and installing all my metalsmith devdependencies fresh. that seemed to do it.

`npm install metalsmith metalsmith-templates metalsmith-markdown metalsmith-drafts metalsmith-collections --save-dev`

**Comment by ianstormtaylor** [comment]
Hey thanks for this sorry for the delay. Now that https://github.com/superwolff has split out this plugin into two separate plugins—[layouts](https://github.com/superwolff/metalsmith-layouts) and [in-place](https://github.com/superwolff/metalsmith-in-place)—I'm going to deprecate the `metalsmith-templates` plugin, so that we can use the simpler ones instead. I'm going to close this issue, but feel free to re-open there!

Added a deprecation notice to the [readme](https://github.com/segmentio/metalsmith-templates/blob/master/Readme.md).
